# FAS-Bus application main docker compose file
# Run the install script to set password, change variables


version: "3.9"
services:
    #
    # MAIN SERVICES
    #
    
    # Database module
    dbcore:
        build: https://github.com/Projeto-Onibus/FAS-Bus-database.git
        volumes:
            - database_data:/var/lib/postgresql/data 
        environment: 
            POSTGRES_PASSWORD:  # Set the same password as in the main.conf file
        secrets:
            - configurations
    
    # Cache module
    cache:
        image: redis
        resources:
            limits:
                memory: 1G

    # Visualization module
    vizualization:
        build: ./API-Consulta
        ports:
            - "9000:80" # Set the API interface public port, the default 80 may require root privileges

    # Insertion module
    insertion:
        build: ./Insercao-dados            
        volumes: 
            - collected_data:/collect_bus_old

        secrets:
            - configurations
                
    # Correction module
    correction:
        build: ./Bus-trajectory-correction

    #
    # Other utilities
    # 

    # Database administration platform
    adminer:
        image: adminer
        ports:
            - '8088:8080'

    # Advanced data visualization platform
    grafana:
        image: grafana/grafana
        ports:
            - '3000:3000'


volumes:
    database_data:
    collected_data:
    

secrets:
    configurations:
        file: main.conf
