services:
  bus:
    build:
      context: ./FAS-Buses
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=buses
      - POSTGRES_USER=buses
      - POSTGRES_DB=buses
    volumes:
      - "./FAS-Buses/app/:/app/"

  gw:
    build:
      context: ./FAS-Gateway
    ports:
      - '8080:5000'
    volumes:
      - "./FAS-Gateway/app/:/app/"


  db:
    build:
      context: ./FAS-Bus-Database/
    environment:
      - POSTGRES_PASSWORD=12345
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./FAS-Bus-Database/data:/var/data/init_data/
    ports:
      - '15432:5432'

  broker:
    image: rabbitmq:3

  cache:
    image: redis:latest

  logger:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    
    volumes:
      - grafana_data:/var/lib/grafana

    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://logger:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000" 


volumes:
  db_data:
  grafana_data:

secrets:
  db_password:
    file: ./db_password
