# FAS-Bus application main docker compose file
# Run the install script to set password, change variables


version: "3.9"
services:
    #   
    # MAIN SERVICES
    #
    
    # Database module
    dbcore:
        image: fdms3741/fasbus-database
        volumes:
            - database_data:/var/lib/postgresql/data 
        environment: 
            POSTGRES_PASSWORD:  ${DATABASE_PASSWORD}
        secrets:
            - main_configurations
    
    # Cache module
    cache:
        image: redis
        #resources:
        #    limits:
        #        memory: 1G

    # Static site and API reverse proxy
    vizualization:
        image: fdms3741/fasbus-site
        ports:
            - "${API_PORT}:80" # Set the API interface public port, the default 80 may require root privileges

    # API core
    api:
        image: fdms3741/fasbus-visualization
        secrets:
            - main_configurations

    # Insertion module
    insertion:
        image: fdms3741/fasbus-rio-insertion       
        volumes: 
            - collected_data:/collect_bus_old
        environment:
            TZ: ${LOCAL_TIMEZONE}
         #   DATABASE_USERNAME: 
         #   DATABASE_PASSWORD: 
         #   DATABASE_NAME:
         #   DATABASE_HOST: 
        secrets:
            - main_configurations
                
    # Correction module
    correction:
        image: fdms3741/fasbus-correction

volumes:
    database_data:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: ${DATABASE_PATH}
    collected_data:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: ${RAW_DATA_PATH}
    

secrets:
    main_configurations:
        file: main.conf
