# FAS-Bus application main docker compose file
# Run the install script to set password, change variables


version: "3.9"
services:

    # ---------------------------------------------------------
    # FAS-Bus modules
    # ---------------------------------------------------------

    # Database module
    dbcore:
        ~version~: ${DATABASE_MODULE_SOURCE}
        volumes:
            - database_data:/var/lib/postgresql/data 
        environment: 
            POSTGRES_PASSWORD:  ${DATABASE_PASSWORD}
        secrets:
            - main_configurations
    
    # Static site and API reverse proxy
    vizualization:
        ~version~: ${PROXY_MODULE_SOURCE}
        ports:
            - "${API_PORT}:80" # Set the API's exposed public port

    # API core
    api:
        ~version~: ${API_MODULE_SOURCE}
        secrets:
            - main_configurations

    # Insertion module
    insertion:
        ~version~: ${INSERTION_MODULE_SOURCE}       
        volumes: 
            - collected_data:/collect_bus_old
        environment:
            TZ: ${LOCAL_TIMEZONE}
        secrets:
            - main_configurations
                
    # Correction module
    correction:
        ~version~: ${CORRECTION_MODULE_SOURCE}
        deploy:
            resources:
              reservations:
                devices:
                   - capabilities: [gpu]


    #   
    # Essencial services 
    #
    
    # Cache module
    cache:
        image: redis
        #resources:
        #    limits:
        #        memory: 1G

#

volumes:
    database_data:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: ${DATABASE_PATH}
    collected_data:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: ${RAW_DATA_PATH}
    

secrets:
    main_configurations:
        file: main.conf
